server:
  port: 7005


eureka:
  instance:
    appname: order-service
    app-group-name: order-service
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/


management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  boot:
    admin:
      context-path: /admin