server:
  port: 7000


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
  instance:
    hostname: localhost
    appname: product-service
    app-group-name: product-service
spring:
  application:
    name: product-service

#  profiles:
#    active: peer2