server:
  port: 7002


eureka:
  client:
    service-url:
      # defaultZone: http://node101:8001/eureka/
      defaultZone: http://localhost:8000/eureka/
  instance:
    # hostname: node101
    appname: product-service
    app-group-name: product-service
    hostname: localhost
spring:
  application:
    name: product-service