server:
  port: 7001


eureka:
  client:
    service-url:
      defaultZone: http://node100:8000/eureka/
  instance:
    hostname: node100
    appname: product-service
    app-group-name: product-service
spring:
  application:
    name: product-service