server:
  port: 7003


eureka:
  client:
    service-url:
      # defaultZone: http://node102:8002/eureka/
      defaultZone: http://localhost:8000/eureka
  instance:
    # hostname: node102
    appname: product-service
    app-group-name: product-service
    hostname: localhost
spring:
  application:
    name: product-service