server:
  port: 7002


eureka:
  client:
    service-url:
      defaultZone: http://node101:8001/eureka/
  instance:
    hostname: node101
    appname: product-service
    app-group-name: product-service
spring:
  application:
    name: product-service