server:
  port: 8000
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: false
  instance:
    appname: eureka-server
    hostname: localhost
    app-group-name: eureka-server