server:
  port: 8001
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://node100:8000/eureka/,http://node102:8002/eureka/
  server:
    enable-self-preservation: true
    # 服务剔除时间
    eviction-interval-timer-in-ms: 10000
  instance:
    appname: eureka-server
    hostname: node101
    app-group-name: eureka-server
spring:
  application:
    name: eureka-server