server:
  port: 6003


#eureka:
#  client:
#    service-url:
#      defaultZone: http://node100:8000/eureka/
#    register-with-eureka: true
#    fetch-registry: true
#  instance:
#    hostname: node102
#    appname: pay-service
#    app-group-name: pay-service


